[package]
name = "chriswhealy/sha3"
version = "1.3.6"
license = "MIT"
description = "Calculates the SHA3 hash of a local file, implemented in WebAssembly Text"
repository = "https://github.com/ChrisWhealy/wasm_sha3"
readme = "./README.md"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = "sha3"
source = "./bin/sha3.prod.opt.wasm"
abi = "wasi"

[[command]]
name = "224"
module = "sha3"
runner = "wasi"
[command.annotations.wasi]
main_args = ["224"]

[[command]]
name = "256"
module = "sha3"
runner = "wasi"
[command.annotations.wasi]
main_args = ["256"]

[[command]]
name = "384"
module = "sha3"
runner = "wasi"
[command.annotations.wasi]
main_args = ["384"]

[[command]]
name = "512"
module = "sha3"
runner = "wasi"
[command.annotations.wasi]
main_args = ["512"]

[[command]]
name = "shake128"
module = "sha3"
runner = "wasi"
[command.annotations.wasi]
main_args = ["shake128"]

[[command]]
name = "shake256"
module = "sha3"
runner = "wasi"
[command.annotations.wasi]
main_args = ["shake256"]
